# Generated by Django 4.0.3 on 2022-05-28 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('Image_Id', models.AutoField(primary_key=True, serialize=False)),
                ('User_Id', models.IntegerField(default=0, null=True)),
                ('Face_Id', models.IntegerField(default=0, null=True)),
                ('Image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(help_text='Enter your Full name', max_length=100)),
                ('Family_Name', models.CharField(help_text='Enter your Full name', max_length=100)),
                ('Phone', models.CharField(help_text='Username', max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10)),
                ('Image', models.ImageField(null=True, upload_to='images')),
                ('is_found', models.BooleanField(blank=True, default=False, null=True)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Found',
            fields=[
                ('Found_Id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(help_text='Enter your Full name', max_length=100)),
                ('Family_Name', models.CharField(help_text='Enter your Full name', max_length=100)),
                ('Phone', models.CharField(help_text='Username', max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10)),
                ('Image', models.ImageField(null=True, upload_to='images')),
                ('is_identified', models.BooleanField(blank=True, default=False, null=True)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_by', models.CharField(blank=True, max_length=50)),
                ('comment_content', models.CharField(blank=True, max_length=200)),
                ('comment_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Finder.post')),
            ],
            options={
                'ordering': ['-comment_date'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('User_Id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(help_text='Enter your Full name', max_length=100)),
                ('Family_Name', models.CharField(help_text='Enter your Full name', max_length=100)),
                ('Phone', models.CharField(help_text='Username', max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10)),
                ('Image', models.ImageField(null=True, upload_to='images')),
                ('Found', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finder.found')),
                ('Lost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finder.lost')),
            ],
        ),
    ]
